source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

workspace 'uMovie.xcworkspace'
project 'uMovie.xcodeproj'

# For All Targets
def all_targets

end

# Project Pods
def project_pods
    pod 'Alamofire', '~> 5.4'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'IQKeyboardManager', '~> 6.5'
    pod 'Kingfisher', '~> 6.0'
    pod 'SwiftGen', '~> 6.0'
    pod 'SnapKit', '~> 5.0.0'
end

# Test Pods
def test_pods

end

# uMovie Target
target 'uMovie' do
  all_targets
  project_pods      
end

# uMovieTests Target
target 'uMovieTests' do
  all_targets
  test_pods
end

# inhibit_all_warnings!
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      end
  end
end
